### ISSUE TITLE
Bug in wait_for_downloads method using Edge

### ISSUE THREAD

**Issue by joao-voltarelli** [botcity-dev/botcity-framework-web-python#23]
**Describe the bug**
- Using Edge, when the wait_for_downloads method is used an exception related to the javascript command is thrown. The downloads page opens but execution stops after that.

**Expected behavior**
- The method checks the downloads correctly, and the bot execution continues normally.

**Steps to Reproduce**
- Try to download any content using Edge browser.
- Use wait_for_downloads method after that.

**Possible Solution**
- At first, the problem is happening because the Edge downloads page is being accessed the same way it is done in Chrome. Probably changing the javascript command responsible for checking the downloads should solve the problem.

**My Platform**
- OS Version: Windows 10 Home - 21H1
- Python Version: 3.10.1
- Packages Version: botcity-framework-web: 0.3.1

**Additional context**

**Comment by hhslepicka** [comment]
Solved via #25
