### ISSUE TITLE
botcity-captcha-plugin

### ISSUE THREAD

**Issue by Regortech** [botcity-dev/botcity-framework-web-python#48]
I need to pass a captcha in internet explorer.

I want to use botcity-captcha-plugin 0.1.2
can you share a sample code? In the examples I saw a code like BotAntiCaptchaPlugin(os.getenv("ANTICAPTCHA_KEY")) .
What is ANTIAPTCHA_KEY? can you explain this

**Comment by hhslepicka** [comment]
Closed as duplicate of https://github.com/botcity-dev/botcity-plugins-python/issues/1
