### ISSUE TITLE
IE browser vision element not clicked.

### ISSUE THREAD

**Issue by ArzuPinarcioglu** [botcity-dev/botcity-framework-web-python#50]
Hi, I am using IE as browser. Although it finds the elements using vision in the UI, it does not click. It correctly locates the web element.
I think the mouse_move function doesn't work in IE so it can't click

<img width="817" alt="Screen Shot 2022-03-21 at 11 33 35" src="https://user-images.githubusercontent.com/56064611/159227215-e5d1a1ff-97c2-41dd-ad1e-875a7cf0ac09.png">
.

**Comment by lf2a** [comment]
Hi @ArzuPinarcioglu!

I am investigating this problem and at first, it seems to be something to do with the screen resolution.
Do you tried reducing your screen resolution?

**Comment by lf2a** [comment]
Hi!
This issue is caused if you don't change the scale percentage to 100%.

![Capturar](https://user-images.githubusercontent.com/51935281/160122162-d3845ccc-8141-444e-8c26-39aa702f637c.PNG)
[IE Driver documentation](https://www.selenium.dev/documentation/ie_driver_server/)

**Comment by lf2a** [comment]
If the problem persists, open a new issue.
