### ISSUE TITLE
Add Undetectable Chrome as supported Browser

### ISSUE THREAD

**Issue by hhslepicka** [botcity-dev/botcity-framework-web-python#68]
**What's the problem this feature will solve?**
This will allow us to use the framework web with Undetectable Chrome Driver and take advantage of its capabilities to not be detected.

**Describe the solution you'd like**
Add Undetectable ChromeDriver as a **NEW** browser. We must still support the vanilla Chrome Driver. 

**Additional context**
Undetectable Chrome Driver - https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by hhslepicka** [comment]
This depends on #67

**Comment by kayqueGovetri** [comment]
Fixed via #74
