### ISSUE TITLE
Google Chrome on Retina Displays returns the wrong display size.

### ISSUE THREAD

**Issue by hhslepicka** [botcity-dev/botcity-framework-web-python#81]
**Describe the bug**
Similar to what happens with the core framework, under Retina displays, Chrome returns an image that is double the size reported by the viewport, which causes the screenshot to be cut in 1/4.

**Possible Solution**
Port the solution implemented for the framework core in here as well.

**Comment by kayqueGovetri** [comment]
FIX in [commit](https://github.com/botcity-dev/botcity-framework-web-python/commit/1a7b6fc6ecca95cfe0c8cbe861a1283a01e9d901)
